### ISSUE TITLE
有考虑过双流join么?

### ISSUE THREAD

**Issue by zhonghui001** [harbby/sylph#4]
spark的结构流有现成的东西,但是从你的文档中,未发现有这个说明

**Comment by harbby** [comment]
@zhonghui001  StreamSql目前基于flink sql  FLINK1.4应该就支持双流join了
spark结构流上做双流join 我以前是通过外部redis来做状态缓存的。原生的join应该也是刚支持吧？

**Comment by harbby** [comment]
close this issues
